name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Run Tests
      run: ./gradlew gradle-plugin:plugin:check
    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/reports